<a href="https://colab.research.google.com/github/fchakkapat/Coraline-DE/blob/main/Coraline_DE_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment for DE challenge

## Assignment No.1
- **Python script**  
Import data from the FoodSales sheet into the PostgreSQL database and take all years data to same table and PostgreSQL parameters are as follows:
  - database_name: challenge
  - user: root
  - password: DataEngineer_2023
  - table: food_sales

In [12]:
#Upload data
from google.colab import files
uploaded = files.upload()

Saving de_challenge_data.xlsx to de_challenge_data.xlsx

In [43]:
#Use Pandas library for exploring data analysis and cleansing data
import pandas as pd

In [14]:
#Read excel file from path
path = 'de_challenge_data.xlsx' #Name of data
df = pd.read_excel(path, sheet_name='FoodSales', header=1)
df

,ID,Date,Region,City,Category,Product,Qty,UnitPrice,TotalPrice
0,ID07351,2022-01-01 00:00:00,East,Boston,Bars,Carrot,33,1.77,58.41
1,ID07352,2022-01-04 00:00:00,East,Boston,Crackers,Whole Wheat,87,3.49,303.63
2,ID07353,2022-01-07 00:00:00,West,Los Angeles,Cookies,Chocolate Chip,58,1.87,108.46
3,ID07354,2022-01-10 00:00:00,East,New York,Cookies,Chocolate Chip,82,1.87,153.34
4,ID07355,2022-01-13 00:00:00,East,Boston,Cookies,Arrowroot,38,2.18,82.84
...,...,...,...,...,...,...,...,...,...
242,ID07590,2023-12-18 00:00:00,East,Boston,Cookies,Arrowroot,34,2.18,74.12
243,ID07591,2023-12-21 00:00:00,East,Boston,Cookies,Chocolate Chip,245,1.87,458.15
244,ID07592,2023-12-24 00:00:00,East,Boston,Crackers,Whole Wheat,30,3.49,104.7
245,ID07593,2023-12-27 00:00:00,West,Los Angeles,Bars,Bran,30,1.87,56.1
246,ID07594,2023-12-30 00:00:00,West,Los Angeles,Cookies,Oatmeal Raisin,44,2.84,124.96

In [15]:
#Check data informations
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          246 non-null    object
 1   Date        245 non-null    object
 2   Region      245 non-null    object
 3   City        245 non-null    object
 4   Category    245 non-null    object
 5   Product     245 non-null    object
 6   Qty         245 non-null    object
 7   UnitPrice   245 non-null    object
 8   TotalPrice  245 non-null    object
dtypes: object(9)
memory usage: 17.5+ KB

> As above, All data income and Non-Null Count are different.
**So there must be something wrong.**  
- To do next, Clean for missing value because number of data income is more than non-null count.

In [16]:
#Check for missing value by columns
df.isnull().sum()

ID            1
Date          2
Region        2
City          2
Category      2
Product       2
Qty           2
UnitPrice     2
TotalPrice    2
dtype: int64

In [17]:
#Find missing value
na = pd.isnull(df['Date'])
df[na]

       ID Date Region City Category Product  Qty UnitPrice TotalPrice
122   NaN  NaN    NaN  NaN      NaN     NaN  NaN       NaN        NaN
123  2022  NaN    NaN  NaN      NaN     NaN  NaN       NaN        NaN

In [18]:
#Delete row missing value
df = df.dropna()

In [19]:
#check for missing value again
display(df.isnull().sum())
df.head(125)

ID            0
Date          0
Region        0
City          0
Category      0
Product       0
Qty           0
UnitPrice     0
TotalPrice    0
dtype: int64

,ID,Date,Region,City,Category,Product,Qty,UnitPrice,TotalPrice
0,ID07351,2022-01-01 00:00:00,East,Boston,Bars,Carrot,33,1.77,58.41
1,ID07352,2022-01-04 00:00:00,East,Boston,Crackers,Whole Wheat,87,3.49,303.63
2,ID07353,2022-01-07 00:00:00,West,Los Angeles,Cookies,Chocolate Chip,58,1.87,108.46
3,ID07354,2022-01-10 00:00:00,East,New York,Cookies,Chocolate Chip,82,1.87,153.34
4,ID07355,2022-01-13 00:00:00,East,Boston,Cookies,Arrowroot,38,2.18,82.84
...,...,...,...,...,...,...,...,...,...
120,ID07471,2022-12-27 00:00:00,East,New York,Cookies,Chocolate Chip,65,1.87,121.55
121,ID07472,2022-12-30 00:00:00,West,San Diego,Cookies,Arrowroot,83,2.18,180.94
124,ID,Date,Region,City,Category,Product,Qty,UnitPrice,TotalPrice
125,ID07473,2023-01-02 00:00:00,East,Boston,Cookies,Arrowroot,32,2.18,69.76
126,ID07474,2023-01-05 00:00:00,East,Boston,Bars,Carrot,63,1.77,111.51

> **Clean missing value success.**  
To-do Next, Check for Outlier value from ID column because ID must be unique values.  
- Use Regular expression(Regex) for matching text.

In [20]:
#Find Outlier from ID by regex
#The Pattern of ID column begins with 'ID' followed by a 5-digit number.
regex = '^(ID)\d{5}$'
Inlier = df['ID'].str.match(regex)
df[Inlier==False]

     ID  Date  Region  City  Category  Product  Qty  UnitPrice  TotalPrice
124  ID  Date  Region  City  Category  Product  Qty  UnitPrice  TotalPrice

In [21]:
#Filter out Outlier ID row
df=df[Inlier==True]
df.head(125)

,ID,Date,Region,City,Category,Product,Qty,UnitPrice,TotalPrice
0,ID07351,2022-01-01 00:00:00,East,Boston,Bars,Carrot,33,1.77,58.41
1,ID07352,2022-01-04 00:00:00,East,Boston,Crackers,Whole Wheat,87,3.49,303.63
2,ID07353,2022-01-07 00:00:00,West,Los Angeles,Cookies,Chocolate Chip,58,1.87,108.46
3,ID07354,2022-01-10 00:00:00,East,New York,Cookies,Chocolate Chip,82,1.87,153.34
4,ID07355,2022-01-13 00:00:00,East,Boston,Cookies,Arrowroot,38,2.18,82.84
...,...,...,...,...,...,...,...,...,...
120,ID07471,2022-12-27 00:00:00,East,New York,Cookies,Chocolate Chip,65,1.87,121.55
121,ID07472,2022-12-30 00:00:00,West,San Diego,Cookies,Arrowroot,83,2.18,180.94
125,ID07473,2023-01-02 00:00:00,East,Boston,Cookies,Arrowroot,32,2.18,69.76
126,ID07474,2023-01-05 00:00:00,East,Boston,Bars,Carrot,63,1.77,111.51
127,ID07475,2023-01-08 00:00:00,East,Boston,Snacks,Pretzels,29,3.15,91.35

> **Clean Outlier value success.**  
Then, Convert data type in Date column to datetime type.  
Date column should be a detailed description of the year, month, and day (Basic format).

In [22]:
#Change Date column to datetime type with format YYYY-MM-DD
df['Date'] = pd.to_datetime(df['Date'])
df.tail()

,ID,Date,Region,City,Category,Product,Qty,UnitPrice,TotalPrice
242,ID07590,2023-12-18,East,Boston,Cookies,Arrowroot,34,2.18,74.12
243,ID07591,2023-12-21,East,Boston,Cookies,Chocolate Chip,245,1.87,458.15
244,ID07592,2023-12-24,East,Boston,Crackers,Whole Wheat,30,3.49,104.7
245,ID07593,2023-12-27,West,Los Angeles,Bars,Bran,30,1.87,56.1
246,ID07594,2023-12-30,West,Los Angeles,Cookies,Oatmeal Raisin,44,2.84,124.96

In [23]:
#Check data type(Dtype)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 244 entries, 0 to 246
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          244 non-null    object
 1   Date        244 non-null    datetime64[ns]
 2   Region      244 non-null    object
 3   City        244 non-null    object
 4   Category    244 non-null    object
 5   Product     244 non-null    object
 6   Qty         244 non-null    object
 7   UnitPrice   244 non-null    object
 8   TotalPrice  244 non-null    object
dtypes: datetime64[ns](1), object(8)
memory usage: 19.1+ KB

In [24]:
#Get Cleaned_data
df_clean = df

> **Data has been cleaned success.**  
Next, Connect Postgresql to Import data.

In [25]:
# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 13.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package logrotate.
(Reading database ... 121658 files and directories currently installed.)
Preparing to unpack .../00-logrotate_3.19.0-1ubuntu1.1_amd64.deb ...
Unpacking logrotate (3.19.0-1ubuntu1.1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../01-netbase_6.3_all.deb ...
Unpacking netbase (6.3) ...
Selecting previously unselected package libcommon-sense-perl:amd64.
Preparing to unpack .../02-libcommon-sense-perl_3.75-2build1_amd64.deb ...
Unpacking libcommon-sense-perl:amd64 (3.75-2build1) ...
Selecting previously unselected package libjson-perl.
Preparing to unpack .../03-libjson-perl_4.04000-1_all.deb ...
Unpacking libjson-perl (4.04000-1) ...
Selecting previously unselected package libtypes-serialiser-perl.
Preparing to unpack .../04-libtypes-serialiser-perl_1.01-1_all.deb ...
Unpacking libtypes-serialiser-perl (1.01-1) ...
Selecting previously unselected package libjson-xs-perl.
Preparing to unpack .../05-libjson-xs-perl_4.030-1build3_amd64.deb ...
Unpacking libjson-xs-perl (4.030-1build3) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../06-postgresql-client-common_238_all.deb ...
Unpacking postgresql-client-common (238) ...
Selecting previously unselected package postgresql-client-14.
Preparing to unpack .../07-postgresql-client-14_14.10-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-client-14 (14.10-0ubuntu0.22.04.1) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../08-ssl-cert_1.1.2_all.deb ...
Unpacking ssl-cert (1.1.2) ...
Selecting previously unselected package postgresql-common.
Preparing to unpack .../09-postgresql-common_238_all.deb ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Unpacking postgresql-common (238) ...
Selecting previously unselected package postgresql-14.
Preparing to unpack .../10-postgresql-14_14.10-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-14 (14.10-0ubuntu0.22.04.1) ...
Selecting previously unselected package postgresql.
Preparing to unpack .../11-postgresql_14+238_all.deb ...
Unpacking postgresql (14+238) ...
Selecting previously unselected package sysstat.
Preparing to unpack .../12-sysstat_12.5.2-2ubuntu0.2_amd64.deb ...
Unpacking sysstat (12.5.2-2ubuntu0.2) ...
Setting up logrotate (3.19.0-1ubuntu1.1) ...
Created symlink /etc/systemd/system/timers.target.wants/logrotate.timer → /lib/systemd/system/logrotate.timer.
Setting up libcommon-sense-perl:amd64 (3.75-2build1) ...
Setting up ssl-cert (1.1.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Setting up libtypes-serialiser-perl (1.01-1) ...
Setting up libjson-perl (4.04000-1) ...
Setting up netbase (6.3) ...
Setting up sysstat (12.5.2-2ubuntu0.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline

Creating config file /etc/default/sysstat with new version
update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-collect.timer → /lib/systemd/system/sysstat-collect.timer.
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-summary.timer → /lib/systemd/system/sysstat-summary.timer.
Created symlink /etc/systemd/system/multi-user.target.wants/sysstat.service → /lib/systemd/system/sysstat.service.
Setting up postgresql-client-common (238) ...
Setting up libjson-xs-perl (4.030-1build3) ...
Setting up postgresql-client-14 (14.10-0ubuntu0.22.04.1) ...
update-alternatives: using /usr/share/postgresql/14/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
Setting up postgresql-common (238) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Adding user postgres to group ssl-cert

Creating config file /etc/postgresql-common/createcluster.conf with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
Created symlink /etc/systemd/system/multi-user.target.wants/postgresql.service → /lib/systemd/system/postgresql.service.
Setting up postgresql-14 (14.10-0ubuntu0.22.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Creating new PostgreSQL cluster 14/main ...
/usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/14/main --auth-local peer --auth-host scram-sha-256 --no-instructions
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/14/main ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
update-alternatives: using /usr/share/postgresql/14/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up postgresql (14+238) ...
Processing triggers for man-db (2.10.2-1) ...
 * Starting PostgreSQL 14 database server
   ...done.

In [26]:
# Setup a password `DataEngineer_2023` for username `root`
!sudo -u postgres psql -c "CREATE ROLE root SUPERUSER LOGIN PASSWORD 'DataEngineer_2023';"

CREATE ROLE

In [27]:
# Setup a database with name `challenge` to be used
!sudo -u postgres psql -c 'DROP DATABASE IF EXISTS challenge;'
!sudo -u postgres psql -c 'CREATE DATABASE challenge;'

NOTICE:  database "challenge" does not exist, skipping
DROP DATABASE
CREATE DATABASE

In [39]:
#Connecting to the PostgreSQL Database by using psycopg2 module

import psycopg2

#***Set variables here***
db_name = 'challenge'
db_user = 'root'
db_pw = 'DataEngineer_2023'

try:
      conn = psycopg2.connect(
          database = db_name,
          user = db_user,
          password = db_pw
      )
      cursor = conn.cursor()
      print("Connection established successfully!")
except Exception as e:
      print("Error connecting to the database:", e)

Connection established successfully!

In [29]:
#Create function to create table in database
tb_name1 = 'food_sales'

def create_tables():
  commands = (
  f'''
    DROP TABLE IF EXISTS {tb_name1}
  ''',
  f'''
    CREATE TABLE IF NOT EXISTS {tb_name1} (
          ID VARCHAR(255) PRIMARY KEY,
          Date DATE NOT NULL,
          Region VARCHAR(255) NOT NULL,
          City VARCHAR(255) NOT NULL,
          Category VARCHAR(255) NOT NULL,
          Product VARCHAR(255) NOT NULL,
          Qty INT NOT NULL,
          UnitPrice FLOAT NOT NULL,
          TotalPrice FLOAT NOT NULL )
  ''')
  try:
      cursor = conn.cursor()
      for command in commands :
          cursor.execute(command)
      conn.commit()
      print(f"Table {tb_name1} created successfully")
      cursor.close()
  except Exception as error:
      print("Error: %s" % error)
      conn.rollback()
      cursor.close()

create_tables()

Table food_sales created successfully

In [30]:
#Create function to insert Dataframe into table
def insert_df():
  from psycopg2 import extras

  insert_query = f'''
  INSERT INTO {tb_name1} (
    ID,
    Date,
    Region,
    City,
    Category,
    Product,
    Qty,
    UnitPrice,
    TotalPrice)
  VALUES %s
  '''
  print(f"*START INSERT DATA FROM `FoodSales` Format `sheet` INTO `{tb_name1}` Format Postgresql database*")
  try:
    cursor = conn.cursor()
    extras.execute_values(cur=cursor,sql=insert_query,argslist=df_clean.values)
    conn.commit()
    print("the dataframe is inserted >> Success")
    cursor.close()
  except (Exception, psycopg2.DatabaseError) as error:
    print("Error: %s" % error)
    conn.rollback()
    cursor.close()

insert_df()

*START INSERT DATA FROM `FoodSales` Format `sheet` INTO `food_sales` Format Postgresql database*
the dataframe is inserted >> Success

In [31]:
#Check for inserted data in postgresql
cursor = conn.cursor()
query = "SELECT * FROM food_sales"
cursor.execute(query)
result = cursor.fetchall()
columns = ['ID', 'Date', 'Region', 'City', 'Category', 'Product', 'Qty', 'UnitPrice', 'TotalPrice']
pg_df = pd.DataFrame(result, columns=columns)
pg_df

,ID,Date,Region,City,Category,Product,Qty,UnitPrice,TotalPrice
0,ID07351,2022-01-01,East,Boston,Bars,Carrot,33,1.77,58.41
1,ID07352,2022-01-04,East,Boston,Crackers,Whole Wheat,87,3.49,303.63
2,ID07353,2022-01-07,West,Los Angeles,Cookies,Chocolate Chip,58,1.87,108.46
3,ID07354,2022-01-10,East,New York,Cookies,Chocolate Chip,82,1.87,153.34
4,ID07355,2022-01-13,East,Boston,Cookies,Arrowroot,38,2.18,82.84
...,...,...,...,...,...,...,...,...,...
239,ID07590,2023-12-18,East,Boston,Cookies,Arrowroot,34,2.18,74.12
240,ID07591,2023-12-21,East,Boston,Cookies,Chocolate Chip,245,1.87,458.15
241,ID07592,2023-12-24,East,Boston,Crackers,Whole Wheat,30,3.49,104.70
242,ID07593,2023-12-27,West,Los Angeles,Bars,Bran,30,1.87,56.10
243,ID07594,2023-12-30,West,Los Angeles,Cookies,Oatmeal Raisin,44,2.84,124.96

> As above, **Data has been moved from sheet to Postgresql completely**.

In [32]:
# Close connection
cursor.close()
conn.close()

**Assignment No.1 success. **

## Assignment No.2  
- **SQL script**  
create a table: cat_reg, using data from Assignment No.1 .

In [33]:
#Connecting to the PostgreSQL Database
try:
    conn = psycopg2.connect(
        database = db_name,
        user = db_user,
        password = db_pw
    )
    cursor = conn.cursor()
    print("Connection established successfully!")
except Exception as e:
    print("Error connecting to the database:", e)

Connection established successfully!

In [34]:
#Create function to create table name : cat_reg
tb_name2 = 'cat_reg'
def create_tables2():

  table_creation2 = (
    f"""
      DROP TABLE IF EXISTS {tb_name2}
    """,
    f"""
      CREATE TABLE IF NOT EXISTS {tb_name2} (
            Category VARCHAR(255) NOT NULL,
            East INT NOT NULL,
            West INT NOT NULL,
            "Grand Total" INT NOT NULL )
    """)
  try:
      cursor = conn.cursor()
      for tb_c2 in table_creation2 :
        cursor.execute(tb_c2)
      conn.commit()
      print(f"Table {tb_name2} created successfully")
      cursor.close()
  except Exception as error:
      print("Error: %s" % error)
      conn.rollback()
      cursor.close()

create_tables2()

Table cat_reg created successfully

> **table cat_reg** is cross table format,or Excel pivot table.

In [35]:
#Query for check condition pivot table before insert data

query1 = '''
SELECT
  Category,
  SUM(CASE WHEN Region = 'East' THEN TotalPrice END) AS East,
  SUM(CASE WHEN Region = 'West' THEN TotalPrice END) AS West,
  SUM(TotalPrice) AS "Grand_Total"
FROM food_sales
GROUP BY Category
ORDER BY Category;
'''
cursor.execute(query1)
print(cursor.fetchall())

[('Bars', 6355.200000000002, 4180.370000000002, 10535.570000000002), ('Cookies', 10683.5, 6528.909999999999, 17212.41), ('Crackers', 3025.83, 314.1, 3339.9299999999994), ('Snacks', 1459.8300000000002, 777.84, 2237.6699999999996)]

In [36]:
#Create function to insert data into cat_reg table
def insert_data2():
  insert_pv = f'''
  INSERT INTO {tb_name2}
  SELECT
    Category,
    SUM(CASE WHEN Region = 'East' THEN TotalPrice END) AS East,
    SUM(CASE WHEN Region = 'West' THEN TotalPrice END) AS West,
    SUM(TotalPrice) AS "Grand_Total"
  FROM food_sales
  GROUP BY Category
  ORDER BY Category;
  '''
  print(f"*START CREATE DATA FROM `FoodSales` TO `{tb_name2}`*")
  try:
    cursor = conn.cursor()
    cursor.execute(insert_pv)
    conn.commit()
    print("the dataframe is inserted >> Success")
    cursor.close()
  except (Exception, psycopg2.DatabaseError) as error:
    print("Error: %s" % error)
    conn.rollback()
    cursor.close()

insert_data2()

*START CREATE DATA FROM `FoodSales` TO `cat_reg`*
the dataframe is inserted >> Success

In [37]:
#Check result
cursor = conn.cursor()
cursor.execute('SELECT * FROM cat_reg')
tb = cursor.fetchall()
tb_df = pd.DataFrame(tb,columns=['Category','East','West','Grand Total'])
tb_df

   Category   East  West  Grand Total
0      Bars   6355  4180        10536
1   Cookies  10684  6529        17212
2  Crackers   3026   314         3340
3    Snacks   1460   778         2238

> As above, **The total price table has been achieved from using the data from Assignment No.1** .

In [38]:
# Close connection
cursor.close()
conn.close()

*Assignment No.2 success.*

## SQL scripts for Assignment No.2

Command for creating table cat_reg

```
CREATE TABLE IF NOT EXISTS cat_reg (
  Category VARCHAR(255) NOT NULL,
  East INT NOT NULL,
  West INT NOT NULL,
  "Grand Total" INT NOT NULL
);
```

Command for inserting data into cat_reg

```
INSERT INTO cat_reg
  SELECT
    Category,
    SUM(CASE WHEN Region = 'East' THEN TotalPrice END) AS East,
    SUM(CASE WHEN Region = 'West' THEN TotalPrice END) AS West,
    SUM(TotalPrice) AS "Grand_Total"
  FROM food_sales
  GROUP BY Category
  ORDER BY Category;
```